# Generated by Django 5.0.6 on 2024-07-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_remove_message_id_message_mid_room_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='members',
            field=models.ManyToManyField(blank=True, to='chatapp.profile'),
        ),
    ]
