# Generated by Django 5.0.6 on 2024-07-18 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_alter_room_members'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='RoomChat',
        ),
    ]
